# -*- coding: utf-8 -*-
"""Data Preprocessing Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmoWS2WAgK98Y-kN5AMJxUl5p08hHf5e
"""

# import library yang digunakan
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

# load dataset
dataset = pd.read_csv('data/Data.csv')
X = dataset.iloc[:,:-1]
y = dataset.iloc[:, -1]

# cek nan & imputasi

# cek data kategorik & lakukan mapping

# ubah dari dataframe / series pandas menjadi np.array
X = X.values
y = y.values

# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# normalisasi

