# -*- coding: utf-8 -*-
"""Data Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNDO_qpAXjKIKAKYiUriq1g0V_sZfpxg

## Data Preprocessing
"""

# import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# load data
dataset = pd.read_csv('data/Data.csv')

dataset.head()

X = dataset.iloc[:, 1:3].values
y = dataset.iloc[:, 3].values

# cek NaN
dataset.isnull().sum()

# imputasi pada NaN
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
imputer.fit(X) # mean tiap kolom
X_