# -*- coding: utf-8 -*-
"""Euclidean Distance Training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxbLlUKKBJCLgDJOg_UTWZyKcvdyYPvG

## Implementasi Euclidean Distance
"""

import numpy as np
def euclidean_distance(a,b):
    a = np.array(a)
    b = np.array(b)
    #kode anda

    return jarak

# eksekusi bagian ini

a = [0,0,0,0, 5]
b = [1,2,3,4, 10]

jarak = euclidean_distance(a,b)
print("jarak a & b =", jarak)

"""apabila jarak = 5.477225575051661, kode sudah benar"""